/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeRecipeIdRouteImport } from './routes/recipe.$recipeId'

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdRoute = RecipeRecipeIdRouteImport.update({
  id: '/recipe/$recipeId',
  path: '/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/shopping-list': typeof ShoppingListRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/shopping-list': typeof ShoppingListRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/shopping-list': typeof ShoppingListRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add' | '/shopping-list' | '/recipe/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/shopping-list' | '/recipe/$recipeId'
  id: '__root__' | '/' | '/add' | '/shopping-list' | '/recipe/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  ShoppingListRoute: typeof ShoppingListRoute
  RecipeRecipeIdRoute: typeof RecipeRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId': {
      id: '/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  ShoppingListRoute: ShoppingListRoute,
  RecipeRecipeIdRoute: RecipeRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
